package com.example.myrunningapp

object Constants {

    const val SERVICE_START_RESUME = "SERVICE_START_RESUME"
    const val ACTION_PAUSE_SERVICE = "ACTION_PAUSE_SERVICE"
    const val ACTION_STOP_SERVICE = "ACTION_STOP_SERVICE"
    const val NOTIFICATION_CHANNEL_ID= "tracking_channel"
    const val NOTIFICATION_CHANNEL_NAME = "channel"
    const val ACION_SHOW_TRACKING_FRAGMEMTN = "ACION_SHOW_TRACKING_FRAGMEMTN"
    const val NOTIFICATION_SHOW_ACTION  = "NOTIFICATION_SHOW_ACTION"
    const val LOCATION_UPDATE_INTERVAL = 5000L
    const val FASTEST_UPDATE_INTERVAL = 2000L
    const val NOTIFICATION_ID = 1
}